### ISSUE TITLE
How to cancel the action?

### ISSUE THREAD

**Issue by jasonlaw** [TiO-Design/pull_to_reach#2]
I haven't tried this out but definitely will later, great job. Just have one question in mind, how does the user cancel the action? 

Thank you.

**Comment by JulianBissekkou** [comment]
If you focused on an item by scrolling down the only option to cancel the action is to scroll up again. This will get the user back into the initial state where no item is selected.

**Comment by JulianBissekkou** [comment]
I just fixed an issue in the sample app regarding focus cancelation.
(In case you tried the sample application on an android phone and wondered why this is not possible.)

**Comment by saibotma** [comment]
I´ve created another issue #4 regarding the cancelation issue and I have also found another issue that goes hand in hand with it.

**Comment by JulianBissekkou** [comment]
Closing this now since there is no response.
If you need an API to cancel an action in any other way then simply create an issue and describe your use case 😁.
